### ISSUE TITLE
Raw FSR values over SPI?

### ISSUE THREAD

**Issue by 626Pilot** [JohnSL/FSR_Endstop#3]
Hi. I'm working on an AI delta printer calibration fork of Smoothieware. It works really well so far, but only knowing the depth (not X and Y) limits accuracy. It has to assume the probe is hitting at the X and Y where it thinks it is, because it has no actual feedback other than depth.

I have a theory that FSRs might be used to triangulate the X and Y position being touched. I don't know if FSRs have enough accuracy or repeatability, but if they do, it would be great. I ordered one of your boards recently and I'd like to try to get it talking to a Smoothieboard controller over SPI. I know the processor supports that protocol. Do you think the processor is fast enough, and has enough RAM, to continuously stream the FSR values over SPI? I wouldn't have it maintain a running average or anything like that - just have it send numbers over the wire.

**Comment by JohnSL** [comment]
Yes, it should not be a problem to use SPI to send data to a Smoothieboard. Did you want the FSR controller to be the SPI slave or master?

**Comment by 626Pilot** [comment]
I suppose it would be a slave. Given your experience writing the firmware, do you think typical FSRs have enough accuracy/repeatability to triangulate a position to better than 0.04mm? That would be the minimum useful resolution.

**Comment by JohnSL** [comment]
Making a slave would be really easy, so I'll work on getting a version of the firmware that supports SPI. As to accuracy, I think it depends on the machine and speeds involved. The sensor itself doesn't really change in thickness enough to be an issue.

It seems like we should move this discussion to a forum somewhere. If you send me a link of a good place to continue the discussion, I'll move over there.

**Comment by 626Pilot** [comment]
Alright, that makes sense to me. I'd like to invite you to join the SeeMeCNC forums, where some of our members are already using your endstop board. I've posted a thread here: http://forum.seemecnc.com/viewtopic.php?f=82&t=7936

**Comment by 626Pilot** [comment]
I did a mockup and some math, and it seems that this idea is not feasible. The pressure gradient is too small to measure with even poor accuracy, and would be disturbed to the point of unusability by the tiniest environmental disturbance (stepper motor vibrations, someone sneezed two blocks away, etc.)
